package com.josyantl.joblens.shared.application;

public enum ApplicationActivityType {
    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_STATUS_CHANGED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_RESCHEDULED,
    INTERVIEW_STATUS_CHANGED,
    INTERVIEW_FEEDBACK_UPDATED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    NOTE_CREATED,
    NOTE_UPDATED,
    NOTE_DELETED
}
